version: "3.8"
services:
  mysql:
    build: ./db
    ports:
    - target: 3306
      published: 3306
      # I can specify the protocol with protocol: tcp, but that will be the protocol by default anyway
  flask-app:
    build: ./flask-app
    ports:
      - target: 5000
        published: 5000
  nginx:
    image: nginx:latest
    volumes:
    - type: bind
      source: ./nginx
      target: /etc/nginx/nginx.conf
    ports:
      - target: 80
        published: 80
