version: "3.8"
services:
  application:
    build: ./application
  nginx:
    image: nginx:latest
    volumes:
    - type: bind
      source: ./nginx
      target: etc/nginx/nginx.conf
    ports:
      - target: 80
        published: 80
