pipeline{
        agent any
        environment {
            app_version = 'v1'
            rollback = 'false'
        }
        stages{
            stage('Install Docker and Docker Compose'){
                steps{
                    sh "sudo apt-get update"
                    sh "sudo apt install  curl -y"
                    sh "curl https://get.docker.com | sudo bash"
                    sh "sudo apt update"
                    sh "sudo apt install -y curl jq"
                    sh 'sudo curl -L "https://github.com/docker/compose/releases/download/v2.14.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose'
                    sh "sudo chmod +x /usr/local/bin/docker-compose"
                }
            }
            stage('Build Image'){
                steps{
                    dir('jenkins_advanced_tutorial/chaparootodo_client_working') {
                        script{
                            if (env.rollback == 'false'){
                                image = docker.build("upwardrow/chaperoo-frontend")
                            }
                        }
                    }
                }
            }
            stage('Tag & Push Image'){
                steps{
                    script{
                        if (env.rollback == 'false'){
                            docker.withRegistry('https://registry.hub.docker.com', 'docker-hub-credentials'){
                                image.push("${env.app_version}")
                            }
                        }
                    }
                }
            }
            stage('Deploy App'){
                steps{
                    sh "docker-compose pull && docker-compose up -d"
                }
            }
        }
}