pipeline{
        agent any
        stages{
            stage('Clone Repo'){
                steps{
                    checkout([$class: 'GitSCM', branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[url: 'https://gitlab.com/qacdevops/chaperootodo_client']]])
                }
            }
            stage('Install Docker and Docker Compose'){
                steps{
                    sh "sudo apt-get update"
                    sh "sudo apt install  curl -y"
                    sh "curl https://get.docker.com | sudo bash"
                    sh "sudo apt update"
                    sh "sudo apt install -y curl jq"
                    sh 'sudo curl -L "https://github.com/docker/compose/releases/download/v2.14.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose'
                    sh "sudo chmod +x /usr/local/bin/docker-compose"
                }
            }
            stage('Deploy Application'){
                steps{
                    echo "THIS IS STUPID THING TO DO IN PRODUCTION BUT: Database password is ${DB_PASSWORD}"
                    sh "sudo docker-compose pull && sudo -E DB_PASSWORD=${DB_PASSWORD} docker-compose up -d "
                }
            }
        }
        environment{
                DB_PASSWORD="password"
        }
}