pipeline{
        agent any
        stages{
            stage('Clone Repo'){
                steps{
                    sh "git clone https://gitlab.com/qacdevops/chaperootodo_client"
                }
            }
            stage('Install Docker and Docker Compose'){
                steps{
                    sh "curl https://get.docker.com | bash && apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin"
                }
            }
            stage('Deploy Application'){
                steps{
                    sh "sudo docker-compose pull && sudo -E DB_PASSWORD=${DB_PASSWORD} docker-compose up -d"
                }
            }
        }
}